# Generated by Django 4.2.11 on 2024-05-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Opened'), (2, 'In progress'), (3, 'Closed')]),
        ),
    ]
